# Copyright sonygodx@gmail.com. All Rights Reserved.
# -*- coding: utf-8 -*-

from __future__ import annotations

import os
import pprint
from typing import Any, Dict, List


GRAPH_PREFIXES = ("evt_", "fn_", "macro_", "tl_")
MAIN_BP_FILE = "__bp__.bp.py"


def emit_bpy_package(bp: Any, output_dir: str, *, clean_package: bool = True) -> str:
    package_dir = output_dir
    os.makedirs(package_dir, exist_ok=True)

    if clean_package:
        _remove_generated_files(package_dir)

    graph_files: List[str] = []
    for graph in getattr(bp, "_graphs", []):
        graph_file = _graph_file_name(graph.graph_type, graph.name)
        graph_files.append(graph_file)
        graph_stem = _graph_module_stem(graph_file)
        _write_meta_file(os.path.join(package_dir, f"{graph_stem}_meta.py"), graph)
        _write_graph_file(
            os.path.join(package_dir, graph_file),
            graph,
            meta_module_name=f"{graph_stem}_meta",
        )

    _write_main_file(os.path.join(package_dir, MAIN_BP_FILE), bp, graph_files)
    return package_dir


def emit_debug_package(bp: Any, output_dir: str) -> str:
    package_name = getattr(bp, "_name", "") or "CompiledBlueprint"
    package_dir = _resolve_package_dir(output_dir, package_name)
    return emit_bpy_package(bp, package_dir, clean_package=True)


def _resolve_package_dir(output_dir: str, package_name: str) -> str:
    package_dir = output_dir
    if os.path.basename(output_dir) != package_name:
        package_dir = os.path.join(output_dir, package_name)
    return package_dir


def _remove_generated_files(package_dir: str) -> None:
    for file_name in os.listdir(package_dir):
        if file_name == MAIN_BP_FILE or file_name.endswith("_meta.py"):
            os.remove(os.path.join(package_dir, file_name))
            continue
        if not file_name.endswith(".bp.py"):
            continue
        if any(file_name.startswith(prefix) for prefix in GRAPH_PREFIXES):
            os.remove(os.path.join(package_dir, file_name))


def _write_main_file(path: str, bp: Any, graph_files: List[str]) -> None:
    graph_stems = [_graph_module_stem(name) for name in graph_files]
    lines = [
        "# Auto-generated by bpy_compile",
        "import importlib.util",
        "import os",
        "from ue_bp_dsl import Blueprint",
        "",
        "def _load_graph_module(stem):",
        "    path = os.path.join(os.path.dirname(__file__), f\"{stem}.bp.py\")",
        "    spec = importlib.util.spec_from_file_location(f\"_bpy_compile_graph_{stem}\", path)",
        "    if spec is None or spec.loader is None:",
        "        raise ImportError(f\"Cannot load graph module: {path}\")",
        "    module = importlib.util.module_from_spec(spec)",
        "    spec.loader.exec_module(module)",
        "    return module",
        "",
        "_GRAPH_MODULES = [",
        *[f"    _load_graph_module({stem!r})," for stem in graph_stems],
        "]",
        "",
        "bp = Blueprint(",
        f"    path={bp._path!r},",
        f"    parent={bp._parent!r},",
        f"    bp_type={bp._bp_type!r},",
        ")",
        "",
        "# ── Variables ───────────────────────────────────────────",
    ]
    for var in getattr(bp, "_variables", []):
        lines.append(
            f"bp.var({var.name!r}, {var.type_str!r}, container={var.container!r}, default={str(var.default)!r})"
        )
    lines.append("")
    lines.append("# ── Components ──────────────────────────────────────────")
    for comp in getattr(bp, "_components", []):
        args = [
            repr(comp.name),
            f"class_name={comp.class_name!r}",
            f"parent={comp.parent!r}",
        ]
        attach_to_name = getattr(comp, "attach_to_name", None)
        if attach_to_name:
            args.append(f"attach_to_name={attach_to_name!r}")
        properties = getattr(comp, "properties", None) or {}
        if properties:
            args.append(f"properties={properties!r}")
        lines.append(f"bp.component({', '.join(args)})")
    lines.append("")
    lines.append("# ── Interfaces ──────────────────────────────────────────")
    for interface_path in getattr(bp, "_interfaces", []):
        lines.append(f"bp.interface({interface_path!r})")
    lines.append("")
    lines.append("# ── Event Dispatchers ───────────────────────────────────")
    for dispatcher in getattr(bp, "_dispatchers", []):
        lines.append(f"bp.dispatcher({dispatcher.name!r}, params={dispatcher.params!r})")
    lines.append("")
    lines.append("bp.build()")
    lines.append("for _graph_module in _GRAPH_MODULES:")
    lines.append("    _graph_module.register(bp)")
    lines.append("")

    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))


def _write_graph_file(path: str, graph: Any, *, meta_module_name: str) -> None:
    lines = [
        "# Auto-generated by bpy_compile",
        "import importlib.util",
        "import os",
        "from ue_bp_dsl import *",
        "",
        "def _load_meta():",
        f"    meta_path = os.path.join(os.path.dirname(__file__), {meta_module_name + '.py'!r})",
        f"    spec = importlib.util.spec_from_file_location({'_bpy_compile_meta_' + meta_module_name!r}, meta_path)",
        "    if spec is None or spec.loader is None:",
        '        raise ImportError(f"Cannot load meta module: {meta_path}")',
        "    module = importlib.util.module_from_spec(spec)",
        "    spec.loader.exec_module(module)",
        '    return getattr(module, "META", {})',
        "",
        "META = _load_meta()",
        "",
        "def register(bp):",
    ]
    indent = "    "
    if graph.graph_type == "function":
        lines.append(
            f"{indent}with bp.function({graph.name!r}, inputs={graph.inputs!r}, outputs={graph.outputs!r}, pure={graph.is_pure!r}) as g:"
        )
    else:
        lines.append(f"{indent}with bp.event_graph({graph.name!r}) as g:")
    indent = "        "

    node_vars: Dict[str, str] = {}
    for index, node in enumerate(graph.nodes):
        var_name = node.readable_name or f"Node_{index}"
        node_vars[node.uid] = var_name
        lines.append(f"{indent}{var_name} = {_node_ctor(node)}")
        for pin_name, value in node.defaults.items():
            lines.append(f"{indent}{var_name}.pin({pin_name!r}, {value!r})")

    if graph.connections:
        lines.append("")
        for conn in graph.connections:
            src = node_vars.get(conn.src_node_uid)
            dst = node_vars.get(conn.dst_node_uid)
            if not src or not dst:
                continue
            lines.append(f"{indent}{src}[{conn.src_pin!r}] >> {dst}[{conn.dst_pin!r}]")
    lines.append("")

    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))


def _write_meta_file(path: str, graph: Any) -> None:
    meta = {
        "node_guid": _sorted_dict(_graph_node_guid_map(graph)),
        "node_pos": _sorted_dict(_graph_node_pos_map(graph)),
        "pin_alias": _sorted_dict(_graph_pin_alias_map(graph)),
        "pin_id": _sorted_dict(_graph_pin_id_map(graph)),
        "node_props": _sorted_nested_dict(_graph_node_props_map(graph)),
    }
    lines = [
        "# Auto-generated by bpy_compile",
        "",
        "# pin_alias: maps DSL_clean_name -> UE_actual_pin_name",
        "META = " + pprint.pformat(meta, sort_dicts=True, width=120),
        "",
    ]
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))


def _graph_node_guid_map(graph: Any) -> Dict[str, str]:
    return {
        str(node.readable_name): str(node.node_guid)
        for node in getattr(graph, "nodes", [])
        if getattr(node, "readable_name", "") and getattr(node, "node_guid", "")
    }


def _graph_node_pos_map(graph: Any) -> Dict[str, tuple[float, float]]:
    return {
        str(node.readable_name): (node.pos_x, node.pos_y)
        for node in getattr(graph, "nodes", [])
        if getattr(node, "readable_name", "")
    }


def _graph_pin_alias_map(graph: Any) -> Dict[str, str]:
    pin_alias_map: Dict[str, str] = {}
    for node in getattr(graph, "nodes", []):
        readable_name = getattr(node, "readable_name", "")
        if not readable_name:
            continue
        for pin_name, full_pin_name in getattr(node, "pin_aliases", {}).items():
            pin_alias_map[f"{readable_name}.{pin_name}"] = str(full_pin_name)
    return pin_alias_map


def _graph_pin_id_map(graph: Any) -> Dict[str, str]:
    pin_id_map: Dict[str, str] = {}
    for node in getattr(graph, "nodes", []):
        readable_name = getattr(node, "readable_name", "")
        if not readable_name:
            continue
        for pin_name, pin_id in getattr(node, "pin_ids", {}).items():
            pin_id_map[f"{readable_name}.{pin_name}"] = str(pin_id)
    return pin_id_map


def _graph_node_props_map(graph: Any) -> Dict[str, Dict[str, Any]]:
    return {
        str(node.readable_name): dict(node.extra_props)
        for node in getattr(graph, "nodes", [])
        if getattr(node, "readable_name", "") and getattr(node, "extra_props", {})
    }


def _sorted_dict(values: Dict[str, Any]) -> Dict[str, Any]:
    return dict(sorted(values.items(), key=lambda item: item[0]))


def _sorted_nested_dict(values: Dict[str, Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    return {
        outer_key: dict(sorted(inner_value.items(), key=lambda item: item[0]))
        for outer_key, inner_value in sorted(values.items(), key=lambda item: item[0])
    }


def _graph_file_name(graph_type: str, graph_name: str) -> str:
    safe_name = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in graph_name)
    prefix = "fn" if graph_type == "function" else "evt"
    return f"{prefix}_{safe_name}.bp.py"


def _graph_module_stem(file_name: str) -> str:
    if file_name.endswith(".bp.py"):
        return file_name[:-6]
    return os.path.splitext(file_name)[0]


def _node_ctor(node: Any) -> str:
    node_class = node.node_class
    if node_class == "K2Node_FunctionEntry":
        return "g.entry()"
    if node_class == "K2Node_FunctionResult":
        return "g.result()"
    if node_class == "K2Node_IfThenElse":
        return "g.branch()"
    if node_class == "K2Node_VariableGet":
        return f"g.get_var({node.member_name!r})"
    if node_class == "K2Node_VariableSet":
        return f"g.set_var({node.member_name!r})"
    if node_class == "K2Node_CallFunction":
        return f"g.call({node.function_ref!r})"
    if node_class == "K2Node_DynamicCast":
        return f"g.cast({node.target_type!r})"
    if node_class == "K2Node_Select":
        return "g.select()"
    if node_class == "K2Node_BreakStruct":
        return f"g.break_struct({node.target_type!r})"
    if node_class == "K2Node_SetFieldsInStruct":
        return f"g.set_fields({node.target_type!r})"
    if node_class == "K2Node_Event":
        return f"g.event({node.member_name!r})"
    return f"g.node(type={node_class.removeprefix('K2Node_')!r}, name={node.member_name!r}, target_type={node.target_type!r})"
