from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

from ..ir import BlueprintIR, EdgeIR, GraphIR, NodeIR
from ..parser import parse_blueprint_package


NODE_METHODS_WITH_TARGET = {
    "call", "get_var", "set_var", "break_struct", "make_struct", "event", "custom_event", "cast", "message",
    "switch_enum", "switch_int",
}


def emit_bpy_package_from_upper(upper_dir: str | Path, output_dir: str | Path) -> Path:
    upper = Path(upper_dir).resolve()
    out = Path(output_dir).resolve()
    manifest = upper / "__roundtrip_bpy__.json"
    if not manifest.is_file():
        raise FileNotFoundError(f"Upper package missing ExportBpy CST manifest: {manifest}")
    _assert_safe_upper_output(upper, out)
    payload = json.loads(manifest.read_text(encoding="utf-8"))
    if payload.get("format") != "BpyDecompiler.ExportBpyCst.v2":
        raise ValueError(f"Unsupported roundtrip manifest format in {manifest}")
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True, exist_ok=True)
    _write_root_from_cst(payload, out / "__bp__.bp.py", trailing_blank=True)
    source_name = str(payload.get("source_name") or "Blueprint")
    _write_root_from_cst(payload, out / f"{source_name}.bp.py", trailing_blank=False)
    for graph in payload.get("graphs", []):
        file_name = str(graph.get("file_name") or "")
        if not file_name.endswith(".bp.py") or Path(file_name).name != file_name:
            raise ValueError(f"Unsafe graph file name in manifest: {file_name!r}")
        _write_graph_from_cst(graph, out / file_name)
    return out


def _write_root_from_cst(payload: dict[str, Any], path: Path, *, trailing_blank: bool) -> None:
    root = payload.get("root") or {}
    lines = [
        "# Auto-generated by ExportBpy",
        "import importlib.util",
        "import os",
        "from ue_bp_dsl import Blueprint",
        "",
        "def _load_graph_module(stem):",
        "    file_path = os.path.join(os.path.dirname(__file__), f\"{stem}.bp.py\")",
        "    spec = importlib.util.spec_from_file_location(f\"_exportbpy_graph_{stem}\", file_path)",
        "    if spec is None or spec.loader is None:",
        "        raise ImportError(f\"Cannot load graph module: {file_path}\")",
        "    module = importlib.util.module_from_spec(spec)",
        "    spec.loader.exec_module(module)",
        "    return module",
        "",
        "_GRAPH_MODULES = [",
    ]
    for stem in root.get("graph_modules", []):
        lines.append(f"    _load_graph_module({_dq(str(stem))}),")
    lines.extend([
        "]",
        "",
        str(root.get("blueprint_call") or "bp = Blueprint(\n    path=\"\",\n    parent=\"\",\n    bp_type=\"Normal\",\n)"),
        "",
        "# ── Variables ───────────────────────────────────────────",
    ])
    lines.extend(root.get("variables", []))
    lines.extend(["", "# ── Class Defaults ──────────────────────────────────────"])
    lines.extend(root.get("defaults", []))
    lines.extend(["", "# ── Inherited Component Defaults ────────────────────────"])
    lines.extend(root.get("inherited_component_defaults", []))
    lines.extend(["", "# ── Components ──────────────────────────────────────────"])
    lines.extend(root.get("components", []))
    lines.extend(["", "# ── Interfaces ──────────────────────────────────────────"])
    lines.extend(root.get("interfaces", []))
    lines.extend(["", "# ── Event Dispatchers ───────────────────────────────────"])
    lines.extend(root.get("event_dispatchers", []))
    lines.extend(["", "bp.build()", "for _graph_module in _GRAPH_MODULES:", "    _graph_module.register(bp)"])
    text = "\n".join(lines) + ("\n\n" if trailing_blank else "\n")
    path.write_text(text, encoding="utf-8", newline="\n")


def _write_graph_from_cst(graph: dict[str, Any], path: Path) -> None:
    if graph.get("is_sidecar"):
        _write_sidecar_graph_from_cst(graph, path)
        return
    file_name = path.name
    meta_name = file_name[:-6] + "_meta.py"
    lines = [
        "# Auto-generated by ExportBpy",
        "import importlib.util",
        "import os",
        "from ue_bp_dsl import *",
        "",
    ]
    if graph.get("has_sidecar_loader"):
        lines.extend(_sidecar_loader_lines())
        lines.append("")
    lines.extend([
        "def _load_meta():",
        f"    meta_path = os.path.join(os.path.dirname(__file__), {_dq(meta_name)})",
        f"    spec = importlib.util.spec_from_file_location({_dq('_exportbpy_meta_' + meta_name[:-3])}, meta_path)",
        "    if spec is None or spec.loader is None:",
        "        raise ImportError(f\"Cannot load meta module: {meta_path}\")",
        "    module = importlib.util.module_from_spec(spec)",
        "    spec.loader.exec_module(module)",
        "    return getattr(module, \"META\", {})",
        "",
        "META = _load_meta()",
        "",
        "def register(bp):",
        f"    with {graph.get('context_expr')} as g:",
        "",
        "        # Nodes",
    ])
    _append_graph_body(lines, graph, indent="        ")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def _write_sidecar_graph_from_cst(graph: dict[str, Any], path: Path) -> None:
    lines = [
        "# Auto-generated by ExportBpy",
        "import importlib.util",
        "import os",
        "from ue_bp_dsl import *",
        "",
    ]
    if graph.get("has_sidecar_loader"):
        lines.extend(_sidecar_loader_lines())
        lines.append("")
    blueprint_call = str(graph.get("blueprint_call") or "bp = Blueprint(path=\"/Engine/Transient/ExportBpyNested\", parent=\"/Script/CoreUObject.Object\", bp_type=\"Normal\")")
    lines.extend([
        "def _build_graph():",
        f"    {blueprint_call}",
        f"    with {graph.get('context_expr')} as g:",
        "        # Nodes",
    ])
    if graph.get("connections"):
        for stmt in graph.get("nodes", []):
            lines.append(f"        {stmt}")
        lines.extend(["", "        # Connections"])
        for stmt in graph.get("connections", []):
            lines.append(f"        {stmt}")
        lines.append("")
    else:
        _append_graph_body(lines, graph, indent="        ", connection_title="Connections")
    for stmt in graph.get("footer", []):
        lines.append(str(stmt))
    lines.extend(["", "GRAPH = _build_graph()", ""])
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def _append_graph_body(lines: list[str], graph: dict[str, Any], *, indent: str, connection_title: str = "Data flow") -> None:
    for stmt in graph.get("nodes", []):
        lines.append(f"{indent}{stmt}")
    data_edges = list(graph.get("data_edges", []))
    exec_edges = list(graph.get("exec_edges", []))
    if data_edges:
        lines.extend(["", f"{indent}# {connection_title}"])
        for stmt in data_edges:
            lines.append(f"{indent}{stmt}")
    if exec_edges:
        lines.extend(["", f"{indent}# Exec flow"])
        for stmt in exec_edges:
            lines.append(f"{indent}{stmt}")
    lines.append("")


def _sidecar_loader_lines() -> list[str]:
    return [
        "def _load_sidecar_graph(stem):",
        "    path = os.path.join(os.path.dirname(__file__), f\"{stem}.bp.py\")",
        "    spec = importlib.util.spec_from_file_location(f\"_exportbpy_sidecar_{stem}\", path)",
        "    if spec is None or spec.loader is None:",
        "        raise ImportError(f\"Cannot load sidecar graph module: {path}\")",
        "    module = importlib.util.module_from_spec(spec)",
        "    spec.loader.exec_module(module)",
        "    return getattr(module, \"GRAPH\")",
    ]


def _assert_safe_upper_output(upper: Path, out: Path) -> None:
    if out == upper or upper in out.parents or out in upper.parents:
        raise ValueError(f"Unsafe output path. upper={upper} output={out}")
    if not any(part.lower() == "tmp" for part in out.parts):
        raise ValueError(f"Compile-back output must be under tmp: {out}")


def emit_structural_bpy_package(exported_dir: str | Path, output_dir: str | Path) -> Path:
    source = Path(exported_dir).resolve()
    out = Path(output_dir).resolve()
    _assert_safe(source, out)
    bp = parse_blueprint_package(source)
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True, exist_ok=True)
    for graph in bp.graphs:
        _write_graph(graph, out / graph.source_path.name)
    root_sidecar = source / f"{source.name}.bp.py"
    if root_sidecar.is_file():
        (out / root_sidecar.name).write_text(root_sidecar.read_text(encoding="utf-8"), encoding="utf-8")
    _write_root(bp, out / "__bp__.bp.py")
    return out


def _assert_safe(source: Path, out: Path) -> None:
    if out == source or source in out.parents or out in source.parents:
        raise ValueError(f"Unsafe output path. source={source} output={out}")
    if not any(part.lower() == "tmp" for part in out.parts):
        raise ValueError(f"Structural compile-back output must be under tmp: {out}")


def _write_root(bp: BlueprintIR, path: Path) -> None:
    lines = [
        "# Auto-generated by ExportBpy",
        "import importlib.util",
        "import os",
        "from ue_bp_dsl import Blueprint",
        "",
        "def _load_graph_module(stem):",
        "    file_path = os.path.join(os.path.dirname(__file__), f\"{stem}.bp.py\")",
        "    spec = importlib.util.spec_from_file_location(f\"_exportbpy_graph_{stem}\", file_path)",
        "    if spec is None or spec.loader is None:",
        "        raise ImportError(f\"Cannot load graph module: {file_path}\")",
        "    module = importlib.util.module_from_spec(spec)",
        "    spec.loader.exec_module(module)",
        "    return module",
        "",
        "_GRAPH_MODULES = [",
    ]
    for stem in bp.graph_stems:
        lines.append(f"    _load_graph_module({stem!r}),")
    lines.extend([
        "]",
        "",
        "bp = Blueprint(",
        f"    path={bp.path!r},",
        f"    parent={bp.parent!r},",
        f"    bp_type={bp.bp_type!r},",
        ")",
        "",
        "# ── Variables ───────────────────────────────────────────",
    ])
    for var in bp.variables:
        kwargs = {k: v for k, v in var.items() if k not in {"name", "type"}}
        lines.append(f"bp.var({var.get('name')!r}, {var.get('type')!r}{_kwargs(kwargs)})")
    lines.extend(["", "# ── Class Defaults ──────────────────────────────────────"])
    for key, value in bp.defaults:
        lines.append(f"bp.default({key!r}, {value!r})")
    lines.extend(["", "# ── Components ──────────────────────────────────────────"])
    for comp in bp.components:
        kwargs = {k: v for k, v in comp.items() if k != "name"}
        lines.append(f"bp.component({comp.get('name')!r}{_kwargs(kwargs)})")
    lines.extend(["", "# ── Interfaces ──────────────────────────────────────────"])
    for interface in bp.interfaces:
        lines.append(f"bp.interface({interface!r})")
    lines.extend([
        "",
        "bp.build()",
        "for _graph_module in _GRAPH_MODULES:",
        "    _graph_module.register(bp)",
        "",
    ])
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def _write_graph(graph: GraphIR, path: Path) -> None:
    meta_name = graph.source_path.name[:-6] + "_meta.py"
    lines = [
        "# Auto-generated by ExportBpy",
        "import importlib.util",
        "import os",
        "from ue_bp_dsl import *",
        "",
        "def _load_meta():",
        f'    meta_path = os.path.join(os.path.dirname(__file__), \"{meta_name}\")',
        f'    spec = importlib.util.spec_from_file_location(\"_exportbpy_meta_{meta_name[:-3]}\", meta_path)',
        "    if spec is None or spec.loader is None:",
        "        raise ImportError(f\"Cannot load meta module: {meta_path}\")",
        "    module = importlib.util.module_from_spec(spec)",
        "    spec.loader.exec_module(module)",
        "    return getattr(module, \"META\", {})",
        "",
        "META = _load_meta()",
        "",
        "def register(bp):",
        f"    with {_graph_context(graph)} as g:",
        "",
        "        # Nodes",
    ]
    for node in graph.nodes.values():
        lines.append(f"        {node.name} = {_node_ctor(node)}")
        for pin, value in node.defaults.items():
            lines.append(f"        {node.name}.pin({_format(pin)}, {_format(value)})")
        for key, value in node.props.items():
            if key in {"FunctionOwnerClass", "NodePurityOverride", "VariableContainer", "VariableKind", "VariableScope", "VariableType", "VariableGuid", "VariableGetIsPure", "StructType", "VisiblePins"}:
                continue
            lines.append(f"        {node.name}.set_extra_prop({key!r}, {value!r})")
    data_edges = [edge for edge in graph.edges if not edge.is_exec]
    exec_edges = [edge for edge in graph.edges if edge.is_exec]
    if data_edges:
        lines.extend(["", "        # Data flow"])
        for edge in data_edges:
            lines.append(f"        {_pin(edge.src)} >> {_pin(edge.dst)}")
    lines.extend(["", "        # Exec flow"])
    for edge in exec_edges:
        lines.append(f"        {_pin(edge.src)} >> {_pin(edge.dst)}")
    lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def _graph_context(graph: GraphIR) -> str:
    if graph.kind == "event_graph":
        return f"bp.event_graph({_dq(graph.graph_name)})"
    args = [_dq(graph.graph_name)]
    kwargs: list[str] = []
    for key, value in graph.context_kwargs.items():
        if key in {"inputs", "outputs"}:
            kwargs.append(f"{key}={_format(value)}")
        elif key == "pure" and value:
            kwargs.append("pure=True")
        elif key not in {"pure"}:
            kwargs.append(f"{key}={_format(value)}")
    return "bp.function(" + ", ".join(args + kwargs) + ")"


def _node_ctor(node: NodeIR) -> str:
    if node.kind in NODE_METHODS_WITH_TARGET:
        if node.kind == "node":
            return f"g.node({_kwargs(node.kwargs).lstrip(', ')})"
        method = {"break_struct": "break_struct", "make_struct": "make_struct", "self_ref": "self_ref"}.get(node.kind, node.kind)
        args = [] if node.target is None else [_format(node.target)]
        kwargs = _kwargs(node.kwargs)
        return f"g.{method}(" + ", ".join(args + ([kwargs.lstrip(', ')] if kwargs else [])) + ")"
    if node.kind == "node":
        return f"g.node({_kwargs(node.kwargs).lstrip(', ')})"
    if node.kind == "self_ref":
        return "g.self_ref()"
    return f"g.{node.kind}()"


def _pin(ref: Any) -> str:
    node = ref.node
    pin = ref.pin
    attr = _pin_attr(pin)
    if attr:
        return f"{node}.{attr}"
    return f"{node}[{pin!r}]"


def _pin_attr(pin: str) -> str | None:
    if pin == "execute":
        return "exec"
    if pin == "self":
        return "self_"
    if pin.replace("_", "").isalnum() and not pin[0].isdigit():
        if pin in {"true", "false"}:
            return pin + "_"
        return pin
    return None


def _format(value: Any) -> str:
    if isinstance(value, str):
        return _dq(value)
    if isinstance(value, tuple):
        return "(" + ", ".join(_format(v) for v in value) + ("," if len(value) == 1 else "") + ")"
    if isinstance(value, list):
        return "[" + ", ".join(_format(v) for v in value) + "]"
    return repr(value)


def _dq(value: str) -> str:
    return repr(value).replace("\\'", "__APOS__").replace("'", "\"").replace("__APOS__", "\\'")


def _kwargs(kwargs: dict[str, Any]) -> str:
    return "".join(f", {key}={_format(value)}" for key, value in kwargs.items() if value is not None)

